project:
  output-dir: _render/spectral

book:
  title: "Exploratory Singular Spectrum Analysis"
  author: "Aly Lamuri"
  chapters:
    - index.qmd
    - results/spectral.qmd

format:
  pdf:
    geometry:
      - top=10mm
      - bottom=10mm
      - left=10mm
      - right=10mm
